name: Deploy update

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm test
        env:
          CI: true
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/github-actions
            sudo git pull
            sudo npm install
            sudo tsc
            sudo rm .env
            sudo touch .env
            sudo echo API_ENDPOINT=${{ secrets.SSH_HOST }} >> .env
            sudo echo API_KEY=${{ secrets.SSH_KEY }} >> .env
            sudo cat .env
            sudo pm2 restart dist/server.js
